"""Create an atomic, selected-artifact compatibility-spike build context."""
from __future__ import annotations

import argparse
import hashlib
import json
import os
from pathlib import Path
import shutil
import subprocess
import sys
import tempfile
import zipfile

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))
from services.llm.provisioning.artifacts import SPECS, inventory, manifest, spec, validate, verify_manifest

OLLAMA_URL = "https://github.com/ollama/ollama/releases/download/v0.11.6/ollama-linux-amd64.tgz"
OLLAMA_SHA256 = "fa9608a428c7d6bd46fce69f7016242feedf60fba1a57d3ee767257b071216f6"
OWNER = ".compatibility-spike-owned"


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _wheel_requirement(path: Path) -> str:
    with zipfile.ZipFile(path) as wheel:
        metadata = next(name for name in wheel.namelist() if name.endswith(".dist-info/METADATA"))
        fields = {}
        for line in wheel.read(metadata).decode("utf-8").splitlines():
            if not line:
                break
            if ": " in line:
                key, value = line.split(": ", 1)
                fields.setdefault(key, value)
    return f"{fields['Name']}=={fields['Version']} --hash=sha256:{_sha256(path)}"


def _write_lock(wheelhouse: Path, lock: Path) -> None:
    wheels = sorted(wheelhouse.glob("*.whl"))
    if not wheels:
        raise RuntimeError("pip resolved no wheel files")
    lock.write_text("# Generated by prepare.py; all resolved CPython 3.12 linux wheels are pinned.\n" +
                    "\n".join(_wheel_requirement(wheel) for wheel in wheels) + "\n", encoding="utf-8")


def _copy_selected(source: Path, destination: Path, model: str) -> dict:
    entry = inventory(spec(model, source))
    validate(entry)  # Never create a partial context.
    for relative in SPECS[model]:
        target = destination / relative
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source / relative, target)
    return entry


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--smollm-root", type=Path, required=True)
    parser.add_argument("--coedit-root", type=Path, required=True)
    parser.add_argument("--gector-root", type=Path, required=True)
    parser.add_argument("--download", action="store_true", help="resolve and download all candidate wheels and Ollama")
    args = parser.parse_args()
    output = args.output.resolve()
    if output.exists() and not (output / OWNER).is_file():
        raise SystemExit(f"refusing to replace non-owned output directory: {output}")
    output.parent.mkdir(parents=True, exist_ok=True)
    roots = {"SmolLM": args.smollm_root.resolve(), "CoEdIT": args.coedit_root.resolve(), "GECToR": args.gector_root.resolve()}

    with tempfile.TemporaryDirectory(prefix=f".{output.name}.staging-", dir=output.parent) as temporary:
        stage = Path(temporary)
        entries = {model: _copy_selected(source, stage / "models" / model, model) for model, source in roots.items()}
        staged = {model: {**entry, "root": f"/opt/llm/models/{model}"} for model, entry in entries.items()}
        document = manifest(staged)
        (stage / "manifest.json").write_text(json.dumps(document, indent=2, sort_keys=True) + "\n", encoding="utf-8")
        verify_manifest(document, {model: stage / "models" / model for model in roots})
        for name in ("requirements-candidate.txt", "Dockerfile", "spike.py", "rm_spike.py", "model_runtime.py", "input_bounds.py"):
            shutil.copy2(Path(__file__).with_name(name), stage / name)
        shutil.copy2(ROOT / "services/llm/provisioning/artifacts.py", stage / "artifacts.py")
        # Harness-only copies of the canonical contracts/core; production services
        # are not imported or modified by the candidate image.
        for relative in (
            "services/__init__.py", "services/llm/__init__.py",
            "services/llm/providers/__init__.py", "services/llm/providers/input_bounds.py",
            "services/llm/queue/__init__.py", "services/llm/queue/contracts.py",
            "services/llm/resource_manager/__init__.py",
            "services/llm/resource_manager/contracts.py",
            "services/llm/resource_manager/protocol.py",
            "services/llm/resource_manager/state.py",
            "services/llm/resource_manager/core.py",
        ):
            target = stage / relative
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(ROOT / relative, target)
        if not args.download:
            raise SystemExit("--download is required: a build context without a verified wheelhouse is unsafe")
        wheelhouse = stage / "wheelhouse"
        wheelhouse.mkdir()
        subprocess.run([sys.executable, "-m", "pip", "download", "--dest", str(wheelhouse), "--only-binary=:all:",
                        "--implementation", "cp", "--python-version", "312", "--abi", "cp312",
                        "--extra-index-url", "https://download.pytorch.org/whl/cu128", "-r", str(stage / "requirements-candidate.txt")], check=True)
        _write_lock(wheelhouse, stage / "requirements.lock")
        archive = stage / "ollama-linux-amd64.tgz"
        subprocess.run(["curl", "--fail", "--location", "--retry", "5", "--connect-timeout", "30", "--max-time", "900", OLLAMA_URL, "--output", str(archive)], check=True)
        if _sha256(archive) != OLLAMA_SHA256:
            raise SystemExit("Ollama archive SHA-256 mismatch")
        provenance = {"cuda_runtime": "nvidia/cuda:12.8.1-runtime-ubuntu24.04@sha256:ebef3c171eeef0298e4eb2e4be843105edf3b8b0ac45e0b43acee358e8046867", "ollama": {"url": OLLAMA_URL, "sha256": OLLAMA_SHA256}, "wheels": [{"path": item.name, "sha256": _sha256(item)} for item in sorted(wheelhouse.iterdir())]}
        (stage / "provenance.json").write_text(json.dumps(provenance, indent=2, sort_keys=True) + "\n", encoding="utf-8")
        (stage / OWNER).write_text("owned by tools/compatibility/prepare.py\n", encoding="utf-8")
        if output.exists():
            shutil.rmtree(output)
        os.replace(stage, output)
    print(f"candidate context: {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
